// <auto-generated />
using System;
using Consultoria.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consultoria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consultoria.Infrastructure.Entities.Developer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsAvailable").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Specialization").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("Developers");
            });

            modelBuilder.Entity("Consultoria.Infrastructure.Entities.Problem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("EstimatedResponseTime").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IconClass").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("Problems");
            });

            modelBuilder.Entity("Consultoria.Infrastructure.Entities.ConsultationRequest", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AdminNotes").HasColumnType("nvarchar(max)");
                b.Property<int?>("AssignedDeveloperId").HasColumnType("int");
                b.Property<string>("ClientEmail").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("ClientName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("ProblemId").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("AssignedDeveloperId");
                b.HasIndex("ProblemId");
                b.ToTable("ConsultationRequests");
            });
#pragma warning restore 612, 618
        }
    }
}
